### ISSUE TITLE
Broken Pipe Error on Server

### ISSUE THREAD

**Issue by nazarhussain** [igor-alexandrov/wisepdf#13]
Hi, 

My pdf generation code is working fine on dev machines even in production environment. 

But when I deploy the code to the server, it get struck on `Broken Pipe` error.  The complete log trail is:

```
Broken pipe
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/wisepdf-1.2.5/lib/wisepdf/writer.rb:16:in `write'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/wisepdf-1.2.5/lib/wisepdf/writer.rb:16:in `block in to_pdf'
/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/open3.rb:208:in `popen_run'
/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/open3.rb:90:in `popen3'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/wisepdf-1.2.5/lib/wisepdf/writer.rb:14:in `to_pdf'
```

Please let me know any fix for it, I have to fix it in urgent condition.

**Comment by solilin** [comment]
If you use some options marked red \* from list (http://madalgo.au.dk/~jakobt/wkhtmltoxdoc/wkhtmltopdf-0.9.9-doc.html) be careful because these options are only available using patched QT. Otherwise you will be have Broken Pipe Error

Try install wkhtmltopdf with patched QT on your server, it will help you

**Comment by nazarhussain** [comment]
I removed all those options marked `*` in documentation. But still it is causing the same error. That is the code that came in log. 

```
result, err = Open3.popen3(invoke) do |stdin, stdout, stderr|
        stdin.binmode
        stdin.write(string)
        stdin.close
        [stdout.read, stderr.read]
      end
```

and actual code line is `stdin.write(string)`, So I think its not on `wkhtmltopdf` error, there is problem in writing data to `stdin`, Is there any security permissions involved in it?

**Comment by igor-alexandrov** [comment]
Can you show us full log please? Also it will be good to know parameters that are passed to wkhtmltopdf.
Thanks.

**Comment by nazarhussain** [comment]
The full command that is been used by wisepdf is: 

```
"/usr/bin/wkhtmltopdf" "--margin-bottom" "0" "--margin-top" "0" "--margin-left" "0" "--margin-right" "0" "--page-size" "A4" "--redirect-delay" "3000" "--quiet" "-" "-"
```

The full log for the error is:

```
rake aborted!
Broken pipe
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/wisepdf-1.2.5/lib/wisepdf/writer.rb:16:in `write'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/wisepdf-1.2.5/lib/wisepdf/writer.rb:16:in `block in to_pdf'
/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/open3.rb:208:in `popen_run'
/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/open3.rb:90:in `popen3'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/wisepdf-1.2.5/lib/wisepdf/writer.rb:14:in `to_pdf'
/home/deploy/apps/mil/releases/20121107110512/lib/tasks/mil/send_reports_weekly.rake:27:in `block (3 levels) in <top (required)>'
/home/deploy/apps/mil/releases/20121107110512/lib/tasks/mil/send_reports_weekly.rake:6:in `each'
/home/deploy/apps/mil/releases/20121107110512/lib/tasks/mil/send_reports_weekly.rake:6:in `block (2 levels) in <top (required)>'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/bin/rake:23:in `load'
/home/deploy/apps/mil/shared/bundle/ruby/1.9.1/bin/rake:23:in `<main>'
```

**Comment by nazarhussain** [comment]
The code line from which this error raises is:

``` ruby
 pdf = Wisepdf::Writer.new.to_pdf(html, {
            :margin => {:top => 0, :left => 0, :bottom => 0, :right => 0},
            :page_size => 'A4',
            :no_background => false,
            :disable_external_links => false
        })
```

**Comment by solilin** [comment]
What about version of wkhtmltopdf? With wkhtmltopdf 0.9.9 all is OK with you code

**Comment by nazarhussain** [comment]
Yes I am using `0.9.9` 

```
Name:
  wkhtmltopdf 0.9.9

License:
  Copyright (C) 2008,2009 Wkhtmltopdf Authors.



  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
  This is free software: you are free to change and redistribute it. There is NO
  WARRANTY, to the extent permitted by law.

Authors:
  Written by Jakob Truelsen. Patches by M�rio Silva, Benoit Garret and Emmanuel
  Bouthenot.

```

**Comment by solilin** [comment]
Hm... It is really strangely. What about open console `rails c` and try there

```
html = '<h1>Test</h1>'
pdf = Wisepdf::Writer.new.to_pdf(html, {
            :margin => {:top => 0, :left => 0, :bottom => 0, :right => 0},
            :page_size => 'A4',
            :no_background => false,
            :disable_external_links => false
        })
```

Just in case `chmod +x path_to_wkhtmltopdf`

**Comment by nazarhussain** [comment]
Its been more strange. Your code and my code is running within Rails Console, but since I am using it from a rake task both are giving the same error. 

But on development machine it is running fine. What could be the reason?

**Comment by nazarhussain** [comment]
Have you reached out any conclusion to solve this issue?

**Comment by rqbukhari** [comment]
Having the same issue. I'm using wisepdf with rails 3.2 and having same issue "Broken pipe". Any solution for this issue??

**Comment by muaaznxb** [comment]
I am facing with the same issue.On development machine rake task is running fine but on server it gives error "Broken pipe .Any help will appreciated .

**Comment by muaaznxb** [comment]
Solved the issue by using xvfb-run --server-args="-screen 0, 1280x1024x24" /usr/bin/wkhtmltopdf --use-xserver with wkhtmltopdf version 0.11 rc 1.

**Comment by nazarhussain** [comment]
That's take a lot of trouble shooting, but finally the above solution works.
