### ISSUE TITLE
nill error in render_to_string

### ISSUE THREAD

**Issue by fwoeck** [igor-alexandrov/wisepdf#6]
Hi, when I invoke the library with

``` ruby
   render_to_string pdf: 'Meeting-Report', template: 'meetings/generate_report', layout: 'meeting_report'
```

I get a

```
TypeError: can't convert nil into String
    from /opt/rvm/gems/ruby-1.9.3-p125-perf@livesein_ng/gems/wisepdf-1.2.0/lib/wisepdf/render.rb:47:in `join'
    from /opt/rvm/gems/ruby-1.9.3-p125-perf@livesein_ng/gems/wisepdf-1.2.0/lib/wisepdf/render.rb:47:in `default_pdf_render_options'
    from /opt/rvm/gems/ruby-1.9.3-p125-perf@livesein_ng/gems/wisepdf-1.2.0/lib/wisepdf/render.rb:26:in `render_to_string'
```

replacing line 47 with this:

``` ruby
    def default_pdf_render_options
      Wisepdf::Configuration.options.merge({
        :wkhtmltopdf => nil,
        :layout => false,
        :template => File.join(controller_path || "", action_name || ""),
        :disposition => "inline"
      })
    end
```

fixes it for me.
--Frank

**Comment by igor-alexandrov** [comment]
Thanks for reporting.
Fixed in 1.2.1.
